### ISSUE TITLE
i am trying to return value via module.exports but i get undefined 

### ISSUE THREAD

**Issue by amoled27** [amoled27/bankmanagement#1]
executive.js,  247
customercontoller 38

**Comment by sanketphansekar** [comment]
But I didn't see you using customercontoller in executive.js

**Comment by amoled27** [comment]
hmm yeah yeeah now  i did , see funstion checkID()
go to localhost5000 >> search account >> type account id created >> console.log will show undefined
checkID() returns undefined 


i know that i am doing that wrong , returning while making async calls , but i dont know what to do
